# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 3

# Personal info
name: Harpreet Singh
title: Senior Mobile Application Developer
email: har2008preet@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: Har1994preet
github_username: har2008preet
stackoverflow_username: "3001746"
linkedin_username: har2008preet

# About Section
about_profile_image: images/profile.jpg
about_content: | 
  Hi, my name is Harpreet Singh, and I'm a Senior Mobile Application Developer @ A'alda. I specialize in building robust, scalable mobile apps using React Native and Android Native. With over 6 years of experience, I’ve led teams to create efficient, cross-platform mobile applications and backend systems, focusing on quality and performance. My expertise lies in architecting solutions that enhance user engagement while optimizing for performance across platforms.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: react-native-assistant-context
        link: https://github.com/har2008preet/react-native-assistant-context
        description: |
          This project was initiated as a learning exercise in building reusable components and contexts for React Native. It demonstrates a clean, structured way to manage state and interactions within a React Native application.
      - layout: top-middle
        title: Toastify
        link: https://github.com/collegeduniadevelopers/Toastify
        description: |
          A Singleton implementation of Android Toast with unique enhancements, offering more control over toast duration and appearance. Ideal for mobile apps needing consistent and unobtrusive feedback to users.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: A'alda
        sub_title: Senior Mobile Application Developer
        caption: August 2023 - Present
        description: |
          - Lead the development and maintenance of mobile apps, ensuring scalability and cross-platform compatibility.
          - Built a micro front-end architecture that allows teams to independently develop and release modules over the air.
          - Introduced performance improvements and optimized CI/CD pipelines for seamless deployments across platforms.

      - layout: left
        title: Collegedunia
        link: collegedunia.com
        sub_title: Mobile Engineering Team Lead
        caption: October 2020 - August 2023
        description: |
          - Spearheaded the migration from native Android to React Native for multiple applications, improving development speed and feature parity across iOS and Android.
          - Architected and implemented hybrid WebView integration to seamlessly integrate dynamic web content into mobile apps, enabling rapid content updates without app re-releases.
          - Successfully launched new apps such as KickCash, helping the company expand its offerings and reach new markets.
          - Managed a crash-free rate of over 99%, ensuring a smooth and reliable user experience across all apps.
          
      - layout: left
        title: Collegedunia
        sub_title: Android Developer
        caption: October 2018 - October 2020
        description: |
          - Developed high-traffic Android applications such as Frizza and Pocketcharge, which achieved millions of downloads.
          - Played a key role in optimizing applications for the US market, ensuring compliance with local regulations and user expectations.
          - Maintained and enhanced the Collegedunia app, integrating analytics tools to monitor and improve user engagement metrics.

      - layout: left
        title: Actiwate
        sub_title: Full Stack Developer
        caption: November 2017 - September 2018
        description: |
          - Worked on building robust backend systems using Node.js with Loopback and integrating them with mobile applications.
          - Gained significant experience in DevOps, handling deployment, monitoring, and continuous integration for mobile and backend solutions.
          - Built native Android and hybrid apps using Ionic, with a focus on delivering a smooth and responsive user experience.

      - layout: left
        title: Idecorama
        sub_title: Intern Android Developer
        caption: June 2016 - August 2016
        description: |
          - Developed an Android application from scratch, collaborating with a team to design user-friendly interfaces and integrate API services.
          - Focused on enhancing user experience by optimizing networking layers using Retrofit and crafting intuitive UI designs.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Indian Institute of Information Technology and Management
        caption: 2012 - 2017
        sub_title: B.Tech + M.Tech
        description: |
          Graduated with a dual degree in Information Technology, developing a deep understanding of software engineering principles, networking, and data structures. Gained strong teamwork and leadership skills through various academic and extracurricular projects.

  - title: A Little More About Me
    layout: text
    content: |
      Outside of my professional interests, I’m passionate about:
      - Football (Liverpool FC supporter)
      - Chess
      - Rocket League

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
